version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: laravel-app
    command: >
      bash -c "
        php artisan migrate:refresh --seed && 
        php artisan serve --host=0.0.0.0 --port=8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - laravelnet
    deploy:
      resources:
        limits:
          cpus: '2.0'          # Limita a 1.5 núcleos de CPU
          memory: '1G'        # Limita a 512MB de memória RAM

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "laravel"
    ports:
      - "5432:5432"
    networks:
      - laravelnet
    deploy:
      resources:
        limits:
          cpus: '1.0'          # Limita a 1 núcleo de CPU
          memory: '1G'          # Limita a 1GB de memória RAM

networks:
  laravelnet:
    driver: bridge

volumes:
  postgres_data: